format = """
$cmd_duration$directory$git_branch$aws
  $character"""

palette = "dracula"

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#49628a"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

# Prompt symbols 
[character]
success_symbol = "[ ](bold fg:green)"
error_symbol = "[ ](bold fg:pink)"
vicmd_symbol = "[∮](#f9e2af)"

[fill]
symbol = '-'
style = 'fg:245'

[directory]
style = "bg:blue fg:foreground"
format = '[](fg:blue)[󰉋 → $path]($style)[](fg:blue)'
truncation_length = 2
truncation_symbol = ".../"
home_symbol = " "
read_only = "  "

[git_branch]
#  
symbol = ""
truncation_length = 48
truncation_symbol = ""
format = " 󰜥 []($style)[[$symbol ](bg:orange fg:foreground bold)$branch](bg:orange fg:foreground)[ ]($style)"
style = "fg:orange bold"

[cmd_duration]
min_time = 500
format = "[]($style)[$duration](bg:yellow fg:foreground)[ ]($style)"
style = "fg:yellow"

[hostname]
ssh_only = true
format = "[]($style)[󰣀 ](bg:bold dimmed white fg:#49628a bold)$hostname](bg:bold dimmed white fg:#4c4f69)[ ]($style)"
trim_at = "-"
style = "fg: bold dimmed white"
disabled = false

[aws]
format = "[]($style)[[☁ ](bg:yellow fg:foreground bold) on $profile ($region) $duration](bg:yellow fg:foreground)[ ]($style)"
style = "fg:yellow"

[shell]
fish_indicator = '󰈺 '
nu_indicator = ''

[python]
format = "[]($style)[[🐍 ](bg:#f9e2af fg:#49628a bold) $version](bg:#f9e2af fg:#4c4f69)[ ]($style)"
style = "fg:#f9e2af"
