# bind=SUPER,space,exec,wofi --show drun -o DP-3
# exec-once = hyprctl dispatch submap global
submap=reset
bind=SUPER,space,global,caelestia:launcher
bindt=SUPER,Q,killactive,

bind=SUPER,c,global,caelestia:controlCenter
bind=SUPER,d,global,caelestia:dashboard # short
# bind=ALT,SPACE, submap, caelestia
# submap=caelestia
# bind=,c,global,caelestia:controlCenter
# bindl=, escape, submap, reset
# submap=reset

# bind=SUPER,backspace,exec, hyprlock || hyprctl dispatch exit
# bindl= SUPER,backspace,exec, caelestia shell -d 
bindl= SUPER,backspace,global, caelestia:lock

bindl = SUPER,w,global,caelestia:showall

# Media Control
bind=SUPER,m, submap, media
submap=media
bindl= ,m,global,caelestia:mediaToggle
bindl= ,n,global,caelestia:mediaNext
bindl= ,p,global,caelestia:mediaPrev
bindl=, escape, submap, reset
submap=reset

#Journal
bind = SUPER CTRL, J, exec, caelestia toggle todo
bind=SUPER SHIFT,J,exec,kitty --title fly_is_journal --hold nvim ~/wiki/journal/$(date '+%Y-%m-%d').md
bind=SUPER,j, submap, journal
submap=journal
bind= SHIFT,J,exec, $HOME/dotfiles/hypr/scripts/journal.sh
bindl=, escape, submap, reset
submap=reset

# snipping - copy to clipboard
bind = CTRL, S, exec, bash -c 'grim -g "$(slurp)" - | wl-copy' # snipping - open editor/drawing tool bind 
bind = CTRL SHIFT, S, exec, bash -c 'grim -g "$(slurp)" - | swappy -f -' 
bind=SUPER,P,exec,hyprpicker -n -a

# Workspaces
workspace = 1,monitor:eDP-1 #,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 2,monitor:eDP-1 #,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 3,monitor:eDP-1 #,rounding:true,decorate:true,gapsin:5,gapsout:15
workspace = 4,monitor:DP-1
workspace = 5,monitor:DP-1
workspace = 6,monitor:DP-1
workspace = 7,monitor:DP-2
workspace = 8,monitor:DP-2
workspace = 9,monitor:DP-2

bind=SUPER,1,workspace,7
bind=SUPER,2,workspace,4
bind=SUPER,3,workspace,1
bind=SUPER,4,workspace,8
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,2
bind=SUPER,7,workspace,9
bind=SUPER,8,workspace,6
bind=SUPER,9,workspace,3
bind=SUPER,0,workspace,10

bind=ALT,1,movetoworkspace,7
bind=ALT,2,movetoworkspace,4
bind=ALT,3,movetoworkspace,1
bind=ALT,4,movetoworkspace,8
bind=ALT,5,movetoworkspace,5
bind=ALT,6,movetoworkspace,2
bind=ALT,7,movetoworkspace,9
bind=ALT,8,movetoworkspace,6
bind=ALT,9,movetoworkspace,3
bind=ALT,0,movetoworkspace,10

